name: Build packages

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: push

jobs:

  Build-and-Deploy-Linux:

    name: Build and deploy Linux packages

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    env:
      CONDA_PKG_DIR: ~/conda_pkgs_dir
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Set Env
        run: |
          echo "APT_CACHE_DIR=$RUNNER_TEMP/apt_cache" >> $GITHUB_ENV
          echo "MONTH=$(date +%B)" >> $GITHUB_ENV

      - name: ATP download settings
        run: |
          mkdir -p $APT_CACHE_DIR/partial
          echo Dir::Cache::Archives $APT_CACHE_DIR";" | sudo tee /etc/apt/apt.conf.d/50cacheDir
          echo 'APT::Keep-Downloaded-Packages "true";' | sudo tee /etc/apt/apt.conf.d/10keep-cache

      - name: Cache Conda
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA_PKG_DIR }}
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('conda-env.yaml') }}-${{ env.MONTH }}
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          use-mamba: true
          channels: conda-forge
          pkgs-dirs: ${{ env.CONDA_PKG_DIR }}
      
      - name: Install conda-build
        run: |
          conda install -n base conda-build
    
      - name: Clone and build libsimplerasters
        run: |
          gh repo clone JanCaha/cpp-simplerasters
          cd cpp-simplerasters
          conda build conda
          conda install --use-local libsimplerasters
          cd ..
          rm -rf cpp-simplerasters
      
      - name: Clone and build libviewshed
        run: |
          gh repo clone JanCaha/cpp-viewshed-library -- --recurse-submodules
          cd cpp-viewshed-library
          conda build conda
          conda install --use-local libviewshed
          cd ..
          rm -rf cpp-viewshed-library
      
      - name: Clone and build viewshed
        run: |
          gh repo clone JanCaha/viewshed-library-pybind11
          cd viewshed-library-pybind11
          conda build conda
          conda install --use-local viewshed
          cd ..
          rm -rf viewshed-library-pybind11

      - name: Copy to directory
        run: |
          mkdir -p linux-64
          cp $CONDA/conda-bld/linux-64/*.conda linux-64

      - name: List packages
        run: |
          ls -l linux-64   

      - uses: actions/upload-artifact@v4
        with:
          name: linux-64
          path: linux-64/

  
  Build-and-Deploy-Windows:

    name: Build and deploy Windows packages
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
        
      - uses: conda-incubator/setup-miniconda@v3
        with:
          use-mamba: true
          channels: conda-forge
        
      - name: Install conda-build
        run: |
          conda install -n base conda-build
    
      - name: Clone and build libsimplerasters
        run: |
          gh repo clone JanCaha/cpp-simplerasters
          cd cpp-simplerasters
          conda build conda
          conda install --use-local libsimplerasters
          cd ..
          rmdir /s /q cpp-simplerasters
      
      - name: Clone and build libviewshed
        run: |
          gh repo clone JanCaha/cpp-viewshed-library -- --recurse-submodules
          cd cpp-viewshed-library
          conda build conda
          conda install --use-local libviewshed
          cd ..
          rmdir /s /q cpp-viewshed-library
      
      - name: Clone and build viewshed
        run: |
          gh repo clone JanCaha/viewshed-library-pybind11
          cd viewshed-library-pybind11
          conda build conda
          conda install --use-local viewshed
          cd ..
          rmdir /s /q viewshed-library-pybind11
    
      - name: Copy to directory
        run: |
          mkdir win-64
          copy %CONDA_PREFIX%\conda-bld\win-64\*.conda win-64

      - name: List packages
        run: |
          dir win-64

      - uses: actions/upload-artifact@v4
        with:
          name: win-64
          path: win-64/    

  Build-Conda-Channel-Push-to-GithubPages:

    name: Build Conda Channel and push to GitHub Pages

    runs-on: ubuntu-latest

    needs: [Build-and-Deploy-Linux, Build-and-Deploy-Windows]

    defaults:
      run:
        shell: bash -l {0}
    
    permissions:
      contents: write

    steps:

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          use-mamba: true
          channels: conda-forge

      - name: Install conda-build
        run: |
          conda install -n base conda-build    

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-64
          path: linux-64

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: win-64
          path: win-64

      - name: Conda index
        run: |
          conda index .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: New package versions
            branch: gh-pages
